# for jekyll-github-metadata
repository: trasparente/vigilant-winner

# To have /collection/page/ links
permalink: pretty

# Plugins list
plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-github-metadata

# Exclude from _site
exclude:
  - README.md
  - LICENSE

# Output collection
collections:
  docs:
    output: true

defaults:
  # Set default layout in collections
  - scope:
      type: docs
    values:
      layout: default
  # Turn off page header
  - scope:
      path: ""
    values:
      header: true

# Timezone
timezone: Europe/Rome
