# for jekyll-github-metadata
repository: trasparente/vigilant-winner

# Plugins list
plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-github-metadata

# Exclude from _site
exclude:
  - README.md
  - LICENSE

# Output collection
collections:
  docs:
    output: true

# Timezone
timezone: Europe/Rome
