# for jekyll-github-metadata
repository: trasparente/vigilant-winner

# To have /collection/page/ links
permalink: pretty

# Plugins list
plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-github-metadata

# Exclude from _site
exclude:
  - README.md
  - LICENSE

# Output collection
collections:
  docs:
    output: true

# Set default layout in collections
defaults:
  - scope:
      type: docs
    values:
      layout: default

# Timezone
timezone: Europe/Rome
